# sentry/knowledge/combos.py
#
# Correlation patterns: groups of commands that are individually benign (or only
# mildly suspicious) but malicious *together*. Detected by Stage 2 across the
# whole CSV. `require_shared_artifact=True` means the matched commands must also
# share a file/path/token (proves they're one campaign, not coincidence) and
# escalates them to high confidence; artifact-free combos only escalate to GRAY.
from sentry.models import ComboPattern

COMBO_PATTERNS: list[ComboPattern] = [
    ComboPattern(
        "recon_sweep",
        member_regexes=[r"\bwhoami\b", r"\bnet\s+(user|group|localgroup)\b",
                        r"\bsysteminfo\b", r"\bipconfig\b", r"\bnltest\b",
                        r"\b(quser|qwinsta)\b", r"\btasklist\b"],
        min_members=3, tactic="discovery", mitre_technique="T1082",
        description="Host/account reconnaissance sweep"),
    ComboPattern(
        "ad_recon",
        member_regexes=[r"\bnltest\b", r"\b(dsquery|adfind)\b",
                        r"net\s+group\s+.*domain", r"(get-ad(user|computer|group)|get-domain)",
                        r"(bloodhound|sharphound)"],
        min_members=2, tactic="discovery", mitre_technique="T1087.002",
        description="Active Directory reconnaissance"),
    ComboPattern(
        "linux_recon",
        member_regexes=[r"\buname\b", r"\bid\b", r"/etc/passwd", r"\b(ps\s+aux|ps\s+-ef)\b",
                        r"\b(netstat|ss\s+-)\b", r"\bhostname\b"],
        min_members=3, tactic="discovery", mitre_technique="T1082",
        description="Linux host reconnaissance"),
    ComboPattern(
        "sam_theft_staging",
        member_regexes=[r"reg\s+save\s+hklm\\(sam|system|security)", r"\bcopy\b",
                        r"(compress|makecab|\.zip|\.cab)"],
        min_members=2, tactic="credential-access", mitre_technique="T1003.002",
        description="SAM/SYSTEM credential theft + staging",
        require_shared_artifact=True),
    ComboPattern(
        "ntds_theft",
        member_regexes=[r"(ntdsutil|esentutl.*ntds)", r"vssadmin.*create.*shadow",
                        r"ntds\.dit", r"\bcopy\b.*ntds"],
        min_members=2, tactic="credential-access", mitre_technique="T1003.003",
        description="NTDS.dit Active Directory theft",
        require_shared_artifact=True),
    ComboPattern(
        "lsass_dump_chain",
        member_regexes=[r"(procdump|comsvcs|rundll32).*(lsass|minidump)", r"lsass\.dmp",
                        r"(mimikatz|sekurlsa|pypykatz)"],
        min_members=2, tactic="credential-access", mitre_technique="T1003.001",
        description="LSASS dump then offline parse",
        require_shared_artifact=True),
    ComboPattern(
        "persistence_kit",
        member_regexes=[r"schtasks.*/create", r"\\(temp|appdata|programdata)\\[^\s]+\.(ps1|bat|exe|dll)",
                        r"reg\s+add.*\\run", r"\bsc(\.exe)?\s+create", r"new-service"],
        min_members=2, tactic="persistence", mitre_technique="T1053.005",
        description="Persistence: task/service/run-key + dropped payload"),
    ComboPattern(
        "download_execute",
        member_regexes=[r"(certutil|bitsadmin|iwr|invoke-webrequest|curl|wget).*http",
                        r"\\(temp|appdata|programdata)\\[^\s]+\.(exe|ps1|dll|hta|scr)",
                        r"(rundll32|regsvr32|mshta|wscript|cscript|start)\b"],
        min_members=2, tactic="command-and-control", mitre_technique="T1105",
        description="Download then execute payload",
        require_shared_artifact=True),
    ComboPattern(
        "defense_evasion_combo",
        member_regexes=[r"(wevtutil\s+cl|clear-eventlog)", r"(set-mppreference.*-disable|windefend|amsi)",
                        r"auditpol\s+/(clear|disable)", r"(history\s+-c|\.bash_history)"],
        min_members=2, tactic="defense-evasion", mitre_technique="T1562.001",
        description="Disable defenses + clear logs"),
    ComboPattern(
        "lateral_movement_chain",
        member_regexes=[r"\b(psexec|wmiexec|smbexec)\b", r"wmic\s+/node:",
                        r"net\s+use\s+\\\\", r"(invoke-command|enter-pssession).*-computername",
                        r"schtasks.*/s\s"],
        min_members=2, tactic="lateral-movement", mitre_technique="T1021",
        description="Lateral movement across hosts"),
    ComboPattern(
        "stage_and_exfil",
        member_regexes=[r"(compress-archive|makecab|7z|rar|tar\s+-c|zip\s+-r)",
                        r"(curl|iwr|invoke-webrequest|bitsadmin|scp|rclone).*(http|@|:)",
                        r"copy.*\\\\"],
        min_members=2, tactic="exfiltration", mitre_technique="T1567",
        description="Data staging + exfiltration",
        require_shared_artifact=True),
    ComboPattern(
        "ransomware_impact",
        member_regexes=[r"vssadmin.*delete\s+shadows", r"bcdedit.*recoveryenabled\s+no",
                        r"wbadmin\s+delete", r"wmic\s+shadowcopy\s+delete",
                        r"(net\s+stop|taskkill\s+/f).*(sql|backup|veeam)"],
        min_members=2, tactic="impact", mitre_technique="T1490",
        description="Ransomware: destroy backups + recovery"),
    ComboPattern(
        "kerberoast_chain",
        member_regexes=[r"(getuserspns|kerberoast|rubeus.*kerberoast)", r"\b(klist|kinit)\b",
                        r"\b(hashcat|john)\b"],
        min_members=2, tactic="credential-access", mitre_technique="T1558.003",
        description="Kerberoast then offline crack"),
    ComboPattern(
        "linux_cred_exfil",
        member_regexes=[r"/etc/shadow", r"\bunshadow\b", r"(scp|curl.*-T|rclone)"],
        min_members=2, tactic="credential-access", mitre_technique="T1003.008",
        description="Linux credential theft + exfil"),

    # ===================== Expansion pass (known multi-stage attack playbooks) ==
    ComboPattern(
        "dcsync_golden_ticket",
        member_regexes=[r"(dcsync|lsadump::dcsync|getncchanges)", r"(krbtgt)",
                        r"(kerberos::golden|golden.*ticket|rubeus.*/golden|ticketer)",
                        r"(mimikatz|sekurlsa|lsadump)"],
        min_members=2, tactic="credential-access", mitre_technique="T1558.001",
        description="DCSync krbtgt hash extraction then Golden Ticket forgery"),
    ComboPattern(
        "full_ad_takeover",
        member_regexes=[r"(bloodhound|sharphound)",
                        r"(getuserspns|kerberoast|rubeus.*kerberoast|asreproast|getnpusers)",
                        r"(dcsync|lsadump::dcsync|getncchanges)",
                        r"(kerberos::golden|golden.*ticket|ticketer|/ptt)"],
        min_members=3, tactic="credential-access", mitre_technique="T1558.001",
        description="Human-operated AD takeover: recon -> roast -> DCSync -> ticket forgery"),
    ComboPattern(
        "ransomware_full_chain",
        member_regexes=[r"\b(net\s+(user|group|view)|nltest|adfind|bloodhound)\b",
                        r"(mimikatz|sekurlsa|procdump.*lsass|comsvcs.*minidump|lsass\.dmp)",
                        r"\b(psexec|wmiexec|smbexec)\b|wmic\s+/node:|(invoke-command|enter-pssession).*-computername",
                        r"vssadmin.*delete\s+shadows|wbadmin\s+delete|bcdedit.*recoveryenabled\s+no|wmic\s+shadowcopy\s+delete",
                        r"(net\s+stop|sc\s+stop|taskkill\s+/f).*(sql|veeam|backup|exchange|mssql)"],
        min_members=3, tactic="impact", mitre_technique="T1486",
        description="End-to-end ransomware: recon -> cred dump -> lateral -> backup destruction"),
    ComboPattern(
        "webshell_foothold",
        member_regexes=[r"\\(inetpub|wwwroot|webapps|htdocs|www)\\[^\s]*\.(aspx?|jspx?|php|ashx)",
                        r"(w3wp\.exe|httpd|nginx|tomcat|java).*(cmd|powershell|/bin/sh|/bin/bash)",
                        r"\bwhoami\b|\bipconfig\b|\bnet\s+user\b|\bid\b|\buname\b",
                        r"(certutil|bitsadmin|iwr|invoke-webrequest|curl|wget).*http"],
        min_members=2, tactic="persistence", mitre_technique="T1505.003",
        description="Web shell under web root then server process spawns recon/download"),
    ComboPattern(
        "office_macro_chain",
        member_regexes=[r"(winword|excel|powerpnt|outlook)\.exe",
                        r"(cmd(\.exe)?\s+/c|powershell|wscript|cscript|mshta|regsvr32|rundll32)\b",
                        r"(certutil|bitsadmin|iwr|invoke-webrequest|curl|wget|mshta).*http",
                        r"schtasks.*/create|reg\s+add.*\\run|\bsc(\.exe)?\s+create|new-service"],
        min_members=3, tactic="execution", mitre_technique="T1566.001",
        description="Phishing: Office app spawns LOLBin -> download cradle -> persistence"),
    ComboPattern(
        "rclone_cloud_exfil",
        member_regexes=[r"(7z|rar|winrar|tar\s+-c[a-z]*f?|zip\s+-r|compress-archive)\b",
                        r"\brclone\b.*(copy|sync|move)",
                        r"rclone.*(config|--config|remote:|mega:|drive:|s3:|b2:)"],
        min_members=2, tactic="exfiltration", mitre_technique="T1567.002",
        description="Bulk archive then rclone exfil to cloud storage",
        require_shared_artifact=True),
    ComboPattern(
        "collection_to_staging",
        member_regexes=[r"(findstr\s+.*(/si|/spi).*(password|cred)|grep\s+-[a-z]*r[a-z]*\s+.*(password|secret|api[_-]?key)|select-string.*password)",
                        r"(get-childitem|dir\s+/s|ls\s+-r|tree\b|locate\b).*(\.docx?|\.xlsx?|\.pdf|\.pst|\.csv|\.sql)",
                        r"\b(7z|rar|winrar|tar\s+-c[a-z]*f?|zip\s+-r|compress-archive)\b"],
        min_members=2, tactic="collection", mitre_technique="T1074.001",
        description="Sensitive-file discovery then archive into a staging blob",
        require_shared_artifact=True),
    ComboPattern(
        "byovd_av_kill",
        member_regexes=[r"\\(temp|appdata|programdata|public|windows\\temp)\\[^\s]+\.sys\b",
                        r"(sc(\.exe)?\s+create.*(type=\s*kernel|binpath.*\.sys)|fltmc\s+(load|unload)|reg\s+add.*\\services\\.*imagepath.*\.sys)",
                        r"(set-mppreference.*-disable|sc\s+(stop|delete)\s+windefend|taskkill\s+/f.*(defender|sophos|crowdstrike|sentinel|carbonblack|msmpeng)|net\s+stop.*(defender|sophos))"],
        min_members=2, tactic="defense-evasion", mitre_technique="T1562.001",
        description="BYOVD: drop .sys -> load driver -> terminate EDR/AV",
        require_shared_artifact=True),
    ComboPattern(
        "vss_credential_harvest",
        member_regexes=[r"(vssadmin.*create.*shadow|wmic\s+shadowcopy\s+call\s+create|win32_shadowcopy)",
                        r"(copy|cp)\b.*(harddiskvolumeshadowcopy|globalroot.*shadowcopy)",
                        r"(ntds\.dit|\\sam\b|\\system\b|\\security\b)"],
        min_members=2, tactic="credential-access", mitre_technique="T1003.003",
        description="Create shadow copy then lift NTDS.dit / SAM hive from it",
        require_shared_artifact=True),
    ComboPattern(
        "container_escape",
        member_regexes=[r"docker\s+(run|create).*(--privileged|--pid=host|--net=host|-v\s+/:/|--cap-add)",
                        r"(mount\b.*(/dev/sd|/host)|nsenter\s+.*-t\s+1)",
                        r"(/var/run/docker\.sock|/host/etc|/proc/1/root|release_agent|serviceaccount/token)"],
        min_members=2, tactic="privilege-escalation", mitre_technique="T1611",
        description="Container breakout: privileged run -> mount host -> read host/cloud secrets",
        require_shared_artifact=True),
    ComboPattern(
        "linux_privesc_chain",
        member_regexes=[r"(find\s+/.*-perm\s+-?[0-9]*4000|sudo\s+-l|getcap\s+-r|find\s+/.*-perm\s+-u=s)",
                        r"(cat|cp|less|more|tail)\s+.*/etc/shadow|\bunshadow\b",
                        r"(crontab\s+-|/etc/cron|systemctl\s+enable|/etc/systemd/system/\S+\.service|>>?\s*[~/]?.*\.(bashrc|profile)|authorized_keys)"],
        min_members=2, tactic="privilege-escalation", mitre_technique="T1548.001",
        description="Linux intrusion: SUID/sudo abuse -> /etc/shadow -> cron/systemd/SSH persistence"),
    ComboPattern(
        "spray_then_lateral",
        member_regexes=[r"(crackmapexec|cme|netexec|nxc)\b.*(-p\s|--password|-h\s|pass)",
                        r"(net\s+accounts|get-addefaultdomainpasswordpolicy|net\s+user\s+/domain)",
                        r"\b(psexec|wmiexec|smbexec)\b|(invoke-command|enter-pssession).*-computername|net\s+use\s+\\\\"],
        min_members=2, tactic="credential-access", mitre_technique="T1110.003",
        description="Password spraying then validated lateral movement"),
    ComboPattern(
        "evasion_then_execute",
        member_regexes=[r"(set-mppreference.*-disable|add-mppreference.*exclusion|amsiutils|amsiinitfailed|sc\s+(stop|delete)\s+windefend)",
                        r"-e(xecutionpolicy)?\s*(bypass|unrestricted)|-w(indowstyle)?\s+hidden|-nop(rofile)?\b",
                        r"powershell.*\s-e(nc|ncodedcommand)?\b|frombase64string|certutil.*-decode",
                        r"(iex|invoke-expression)\b|(rundll32|regsvr32|mshta).*(http|javascript:|scrobj)"],
        min_members=3, tactic="defense-evasion", mitre_technique="T1562.001",
        description="Disable defenses + policy bypass + encoded/obfuscated execution"),
    ComboPattern(
        "anti_forensics",
        member_regexes=[r"(wevtutil\s+cl|clear-eventlog|remove-eventlog)",
                        r"(timestomp|set-itemproperty.*(lastwritetime|creationtime)|touch\s+-[acmdrt])",
                        r"(fsutil\s+usn\s+deletejournal|vssadmin.*delete\s+shadows|cipher\s+/w)",
                        r"(history\s+-c|>\s*[~/]?.*\.bash_history|del\s+/[fsq]+|rm\s+.*\.(log|evtx))"],
        min_members=2, tactic="defense-evasion", mitre_technique="T1070",
        description="Anti-forensics: clear logs + timestomp + wipe journals/artifacts"),
    ComboPattern(
        "dll_sideload_chain",
        member_regexes=[r"\\(temp|appdata|programdata|public|users\\public)\\[^\s]+\.dll\b",
                        r"(copy|move|cp)\b.*\.(exe|dll)",
                        r"(rundll32|regsvr32|\.exe)\b.*\\(temp|appdata|programdata|public)\\"],
        min_members=2, tactic="defense-evasion", mitre_technique="T1574.002",
        description="DLL side-loading: drop signed exe + malicious DLL then run",
        require_shared_artifact=True),
    ComboPattern(
        "auth_backdoor",
        member_regexes=[r"net\s+user\s+\S+\s+\S+\s+/add|net\s+user\s+.*/domain.*/add",
                        r"net\s+localgroup\s+(administrators|administradores|domain\s+admins)\s+\S+\s+/add|add-adgroupmember.*admin",
                        r"(reg\s+add.*winlogon.*defaultpassword|skeleton|misc::skeleton|reg\s+add.*specialaccounts.*userlist)"],
        min_members=2, tactic="persistence", mitre_technique="T1136.001",
        description="Account creation + privileged-group add + auth backdoor"),
    ComboPattern(
        "inhibit_recovery_encrypt",
        member_regexes=[r"vssadmin.*delete\s+shadows|wmic\s+shadowcopy\s+delete|wbadmin\s+delete|bcdedit.*recoveryenabled\s+no",
                        r"(net\s+stop|sc\s+stop|taskkill\s+/f).*(sql|veeam|backup|exchange|mssql|sophos)",
                        r"(how[\s_-]*to[\s_-]*decrypt|readme.*decrypt|your files.*encrypted|\.(locked|crypted|encrypted)\b|cipher\s+/w)"],
        min_members=2, tactic="impact", mitre_technique="T1490",
        description="Inhibit recovery + stop DB/backup services + ransom note"),
]
