# sentry/knowledge/standalone.py
#
# Standalone malicious command-line patterns, grounded in:
#   - MITRE ATT&CK Enterprise (technique IDs)
#   - LOLBAS (Windows living-off-the-land binaries & scripts)
#   - GTFOBins (Unix/Linux abusable binaries)
#   - Sigma detection rules & Atomic Red Team
#
# Weighting philosophy (bands: LOW <0.35, GRAY 0.35-0.74, HIGH >=0.75):
#   0.85-0.95  unambiguous attack tooling / destructive actions
#   0.65-0.80  strong LOLBin abuse (network/encoded/credential)
#   0.40-0.60  dual-use / suspicious (needs corroboration or AI review)
#   0.10-0.30  weak signals & recon (only meaningful in a combo)
from sentry.models import Pattern

STANDALONE_PATTERNS: list[Pattern] = [
    # ---------------------------------------------------------------- EXECUTION
    Pattern("ps_encoded", r"powershell.*\s-e(nc|ncodedcommand)?\b", 0.7,
            "T1059.001", "execution", "PowerShell encoded command"),
    Pattern("ps_noprofile", r"powershell.*-nop(rofile)?\b", 0.3,
            "T1059.001", "execution", "PowerShell no-profile"),
    Pattern("ps_exec_bypass", r"-e(xecutionpolicy)?\s*(bypass|unrestricted)", 0.45,
            "T1059.001", "execution", "PowerShell execution-policy bypass"),
    Pattern("ps_iex_download", r"iex\s*\(.*(downloadstring|invoke-webrequest|iwr|downloaddata)", 0.85,
            "T1059.001", "execution", "IEX download-and-execute"),
    Pattern("ps_iex", r"\b(iex|invoke-expression)\b", 0.5,
            "T1059.001", "execution", "Invoke-Expression"),
    Pattern("ps_downloadstring", r"(net\.webclient|new-object\s+net).*downloadstring", 0.7,
            "T1105", "command-and-control", "PowerShell DownloadString cradle"),
    Pattern("ps_frombase64", r"frombase64string", 0.55,
            "T1027", "defense-evasion", "PowerShell base64 decode"),
    Pattern("wscript_cscript", r"\b(wscript|cscript)\b.*\.(vbs|js|wsf|vbe|jse)", 0.5,
            "T1059.005", "execution", "Windows Script Host execution"),
    Pattern("mshta_remote", r"mshta(\.exe)?.*(http|javascript:|vbscript:)", 0.8,
            "T1218.005", "defense-evasion", "mshta remote/scriptlet execution"),
    Pattern("mshta_generic", r"\bmshta(\.exe)?\b", 0.45,
            "T1218.005", "defense-evasion", "mshta proxy execution"),
    Pattern("rundll32_js", r"rundll32.*(javascript:|vbscript:|mshtml)", 0.8,
            "T1218.011", "defense-evasion", "rundll32 script proxy execution"),
    Pattern("regsvr32_remote", r"regsvr32.*(scrobj|/i:http|/i:\\\\)", 0.8,
            "T1218.010", "defense-evasion", "regsvr32 scriptlet (Squiblydoo)"),
    Pattern("installutil", r"installutil.*(/logfile|/u\b|/installtype)", 0.7,
            "T1218.004", "defense-evasion", "InstallUtil proxy execution"),
    Pattern("msbuild_inline", r"msbuild.*\.(xml|csproj|targets|proj)", 0.55,
            "T1127.001", "defense-evasion", "MSBuild inline-task execution"),
    Pattern("wmic_process_call", r"wmic\s+process\s+call\s+create", 0.6,
            "T1047", "execution", "WMI process create"),
    Pattern("mavinject", r"mavinject.*/injectrunning", 0.85,
            "T1055", "defense-evasion", "mavinject process injection"),
    Pattern("curl_pipe_shell", r"\b(curl|wget)\b.*\|\s*(ba)?sh\b", 0.8,
            "T1059.004", "execution", "curl|wget piped to shell"),
    Pattern("bash_c_net", r"\b(bash|sh)\s+-c\b.*(curl|wget|nc\b|/dev/tcp)", 0.6,
            "T1059.004", "execution", "shell -c with network fetch"),
    Pattern("python_c", r"\bpython[0-9.]*\s+-c\b", 0.4,
            "T1059.006", "execution", "python inline code"),
    Pattern("python_revshell", r"(socket\.socket|pty\.spawn|/bin/sh.*subprocess|os\.dup2)", 0.8,
            "T1059.006", "execution", "Python reverse shell"),

    # -------------------------------------------------------------- PERSISTENCE
    Pattern("schtasks_create", r"schtasks.*/create", 0.5,
            "T1053.005", "persistence", "Scheduled task creation"),
    Pattern("at_schedule", r"\bat(\.exe)?\s+(\\\\\S+|[0-9]{1,2}:[0-9]{2})", 0.5,
            "T1053.002", "persistence", "at job scheduling"),
    Pattern("cron_edit", r"(crontab\s+-|/etc/cron|/var/spool/cron|/etc/cron\.d)", 0.5,
            "T1053.003", "persistence", "cron persistence (Linux)"),
    Pattern("reg_runkey", r"reg\s+add.*\\currentversion\\run", 0.6,
            "T1547.001", "persistence", "Registry Run key persistence"),
    Pattern("startup_folder", r"\\start menu\\programs\\startup", 0.55,
            "T1547.001", "persistence", "Startup folder persistence"),
    Pattern("sc_create", r"\bsc(\.exe)?\s+(\\\\\S+\s+)?create\b", 0.6,
            "T1543.003", "persistence", "Windows service creation"),
    Pattern("new_service_ps", r"new-service\b", 0.6,
            "T1543.003", "persistence", "PowerShell New-Service"),
    Pattern("wmi_event_sub", r"(__eventfilter|eventconsumer|register-wmievent|commandlineeventconsumer)", 0.7,
            "T1546.003", "persistence", "WMI event subscription persistence"),
    Pattern("net_user_add", r"net\s+user\s+\S+\s+\S+\s+/add", 0.55,
            "T1136.001", "persistence", "Local account creation"),
    Pattern("localgroup_admin_add", r"net\s+localgroup\s+(administrators|administradores)\s+\S+\s+/add", 0.7,
            "T1098", "persistence", "Add account to local administrators"),
    Pattern("bashrc_persist", r">>?\s*[~/]?.*\.(bashrc|bash_profile|profile|zshrc)\b", 0.55,
            "T1546.004", "persistence", "Shell rc persistence (Linux)"),
    Pattern("ssh_authkeys", r"(authorized_keys|ssh-rsa\s+aaaa|ssh-ed25519)", 0.65,
            "T1098.004", "persistence", "SSH authorized_keys persistence"),
    Pattern("systemd_persist", r"(systemctl\s+enable|/etc/systemd/system/\S+\.service)", 0.45,
            "T1543.002", "persistence", "systemd service persistence (Linux)"),
    Pattern("accessibility_debugger", r"image file execution options.*(sethc|utilman|magnify|osk|narrator)", 0.85,
            "T1546.008", "persistence", "Accessibility-feature debugger hijack"),
    Pattern("winlogon_persist", r"winlogon.*\\(shell|userinit)", 0.7,
            "T1547.004", "persistence", "Winlogon helper persistence"),

    # ------------------------------------------------------ PRIVILEGE ESCALATION
    Pattern("uac_bypass_bin", r"\b(fodhelper|computerdefaults|sdclt|slui|wsreset)(\.exe)?\b", 0.6,
            "T1548.002", "privilege-escalation", "UAC bypass via auto-elevating binary"),
    Pattern("uac_eventvwr", r"eventvwr.*mscfile|hkcu.*mscfile.*shell", 0.7,
            "T1548.002", "privilege-escalation", "UAC bypass via eventvwr hijack"),
    Pattern("setuid_find", r"find\s+/.*-perm\s+-?[0-9]*4000|chmod\s+[ug]?\+?s\b", 0.5,
            "T1548.001", "privilege-escalation", "SUID discovery/abuse (Linux)"),
    Pattern("token_manipulation", r"(incognito|adjusttokenprivileges|impersonateloggedonuser|getsystem)", 0.7,
            "T1134", "privilege-escalation", "Access token manipulation"),
    Pattern("runas_user", r"runas\s+/user:", 0.4,
            "T1134", "privilege-escalation", "runas alternate credentials"),

    # ----------------------------------------------------------- DEFENSE EVASION
    Pattern("hidden_window", r"-w(indowstyle)?\s+hidden", 0.4,
            "T1564.003", "defense-evasion", "Hidden window"),
    Pattern("wevtutil_clear", r"wevtutil\s+cl\b", 0.7,
            "T1070.001", "defense-evasion", "Clear Windows event logs"),
    Pattern("ps_clear_eventlog", r"(clear-eventlog|remove-eventlog|limit-eventlog)", 0.7,
            "T1070.001", "defense-evasion", "PowerShell clear event log"),
    Pattern("auditpol_disable", r"auditpol\s+/(clear|disable)|auditpol.*/success:disable", 0.7,
            "T1562.002", "defense-evasion", "Disable audit policy"),
    Pattern("disable_defender", r"(set-mppreference.*-disable|add-mppreference.*exclusion|"
                                r"sc\s+(stop|delete)\s+windefend|uninstall-windowsfeature.*defender)", 0.85,
            "T1562.001", "defense-evasion", "Disable/blind Windows Defender"),
    Pattern("amsi_bypass", r"(amsiinitfailed|amsiutils|amsicontext|\[ref\]\.assembly\.gettype.*amsi)", 0.85,
            "T1562.001", "defense-evasion", "AMSI bypass"),
    Pattern("disable_firewall", r"netsh\s+(advfirewall|firewall).*(state\s+off|set\s+opmode\s+disable)", 0.7,
            "T1562.004", "defense-evasion", "Disable host firewall"),
    Pattern("clear_bash_history", r"(history\s+-c|>\s*[~/]?.*\.bash_history|unset\s+histfile|histfile=/dev/null|rm\s+.*\.bash_history)", 0.6,
            "T1070.003", "defense-evasion", "Clear shell history (Linux)"),
    Pattern("timestomp", r"(timestomp|set-itemproperty.*(lastwritetime|creationtime)|touch\s+-[acmdrt])", 0.5,
            "T1070.006", "defense-evasion", "Timestomp file timestamps"),
    Pattern("attrib_hidden", r"attrib\s+.*\+[hs]", 0.4,
            "T1564.001", "defense-evasion", "Hide file via attributes"),
    Pattern("chattr_immutable", r"chattr\s+[+-]i", 0.4,
            "T1222.002", "defense-evasion", "chattr immutable (Linux)"),
    Pattern("certutil_decode", r"certutil.*-decode", 0.6,
            "T1140", "defense-evasion", "certutil decode payload"),
    Pattern("encoded_blob", r"[a-z0-9+/]{60,}={0,2}", 0.4,
            "T1027", "defense-evasion", "Long encoded blob"),
    Pattern("temp_exec", r"\\(temp|appdata|programdata|public)\\[^\s]+\.(exe|ps1|bat|vbs|scr|dll|hta)", 0.4,
            "T1036", "defense-evasion", "Execution from temp/appdata"),
    Pattern("fsutil_usn_delete", r"fsutil\s+usn\s+deletejournal", 0.6,
            "T1070", "defense-evasion", "Delete USN change journal"),

    # --------------------------------------------------------- CREDENTIAL ACCESS
    Pattern("hive_dump", r"reg\s+save\s+hk(lm|ey_local_machine)\\(sam|system|security)", 0.9,
            "T1003.002", "credential-access", "Registry hive dump (SAM/SYSTEM/SECURITY)"),
    Pattern("lsass_dump", r"(procdump.*lsass|comsvcs.*minidump|rundll32.*comsvcs.*minidump|"
                          r"out-minidump|dumpert|nanodump)", 0.95,
            "T1003.001", "credential-access", "LSASS memory dump"),
    Pattern("mimikatz", r"(sekurlsa|mimikatz|logonpasswords|kerberos::|crypto::|lsadump)", 0.95,
            "T1003.001", "credential-access", "Mimikatz credential theft"),
    Pattern("ntds_dump", r"(ntdsutil.*ifm|esentutl.*ntds\.dit|esentutl.*/y.*ntds|create\s+full.*ntds)", 0.9,
            "T1003.003", "credential-access", "NTDS.dit Active Directory database theft"),
    Pattern("dcsync", r"(dcsync|lsadump::dcsync|drsuapi|getncchanges)", 0.95,
            "T1003.006", "credential-access", "DCSync domain credential replication"),
    Pattern("secretsdump", r"\bsecretsdump(\.py)?\b", 0.9,
            "T1003", "credential-access", "Impacket secretsdump"),
    Pattern("shadow_read", r"(cat|cp|c>|less|more|tail)\s+.*/etc/shadow", 0.85,
            "T1003.008", "credential-access", "Read /etc/shadow (Linux)"),
    Pattern("unshadow", r"\bunshadow\b", 0.8,
            "T1003.008", "credential-access", "unshadow credential prep (Linux)"),
    Pattern("kerberoast", r"(kerberoast|invoke-kerberoast|getuserspns|tgsrepcrack|rubeus.*kerberoast)", 0.85,
            "T1558.003", "credential-access", "Kerberoasting"),
    Pattern("asreproast", r"(asreproast|getnpusers|rubeus.*asrep)", 0.85,
            "T1558.004", "credential-access", "AS-REP roasting"),
    Pattern("lazagne", r"\blazagne\b", 0.9,
            "T1555", "credential-access", "LaZagne credential harvester"),
    Pattern("browser_creds", r"(login data|cookies\.sqlite|key[34]\.db|logins\.json|\\google\\chrome\\.*login)", 0.7,
            "T1555.003", "credential-access", "Browser credential store access"),
    Pattern("cmdkey_list", r"cmdkey\s+/list", 0.5,
            "T1555", "credential-access", "Enumerate stored credentials"),
    Pattern("vaultcmd", r"vaultcmd\s+/list", 0.5,
            "T1555.004", "credential-access", "Windows Credential Manager enumeration"),
    Pattern("findstr_password", r"(findstr\s+.*(/si|/spi).*(password|passwd|pwd|cred)|select-string.*password)", 0.6,
            "T1552.001", "credential-access", "Search files for passwords"),
    Pattern("grep_password", r"grep\s+-[a-z]*r[a-z]*\s+.*(password|passwd|secret|api[_-]?key)", 0.55,
            "T1552.001", "credential-access", "grep recursive for secrets (Linux)"),
    Pattern("reg_query_autologon", r"reg\s+query.*winlogon.*defaultpassword", 0.7,
            "T1552.002", "credential-access", "Read autologon password from registry"),

    # ----------------------------------------------------------------- DISCOVERY
    # (low weights: individually benign; combos elevate genuine recon sweeps)
    Pattern("recon_whoami", r"\bwhoami\b", 0.15,
            "T1033", "discovery", "whoami enumeration"),
    Pattern("recon_net_query", r"\bnet\s+(user|group|localgroup|accounts|session|view|share)\b", 0.2,
            "T1087", "discovery", "net account/share enumeration"),
    Pattern("recon_systeminfo", r"\bsysteminfo\b", 0.15,
            "T1082", "discovery", "System information discovery"),
    Pattern("recon_ifconfig", r"\b(ipconfig|ifconfig|ip\s+a(ddr)?)\b", 0.1,
            "T1016", "discovery", "Network configuration discovery"),
    Pattern("recon_nltest", r"\bnltest\b", 0.3,
            "T1018", "discovery", "Domain controller enumeration"),
    Pattern("recon_dsquery", r"\b(dsquery|dsget|adfind)\b", 0.4,
            "T1087.002", "discovery", "Active Directory query tooling"),
    Pattern("recon_ad_ps", r"(get-ad(user|computer|group|domain)|get-domain|get-netuser)", 0.35,
            "T1087.002", "discovery", "PowerShell AD enumeration"),
    Pattern("recon_bloodhound", r"(bloodhound|sharphound|invoke-bloodhound)", 0.8,
            "T1087", "discovery", "BloodHound AD attack-path mapping"),
    Pattern("recon_proc_list", r"\b(tasklist|ps\s+-ef|ps\s+aux)\b", 0.1,
            "T1057", "discovery", "Process discovery"),
    Pattern("recon_quser", r"\b(quser|qwinsta|query\s+session|w\s*$|who\b)\b", 0.2,
            "T1033", "discovery", "Logged-on user discovery"),
    Pattern("recon_etc_passwd", r"(cat|less|more|tail|head)\s+.*/etc/passwd", 0.2,
            "T1087.001", "discovery", "Read /etc/passwd (Linux)"),
    Pattern("recon_portscan", r"\b(nmap|masscan|crackmapexec|cme)\b", 0.55,
            "T1046", "discovery", "Network/port scanning"),

    # ---------------------------------------------------------- LATERAL MOVEMENT
    Pattern("psexec", r"\b(psexec|paexec|csexec)(\.exe)?\b", 0.6,
            "T1021.002", "lateral-movement", "PsExec remote execution"),
    Pattern("impacket_exec", r"\b(wmiexec|smbexec|atexec|dcomexec)(\.py)?\b", 0.8,
            "T1021", "lateral-movement", "Impacket remote execution"),
    Pattern("wmic_node", r"wmic\s+/node:", 0.6,
            "T1047", "lateral-movement", "WMIC remote node execution"),
    Pattern("winrm_remote", r"((invoke-command|enter-pssession|new-pssession).*-computername|\bwinrs\b)", 0.5,
            "T1021.006", "lateral-movement", "WinRM/PSRemoting"),
    Pattern("schtasks_remote", r"schtasks.*/s\s+\S+", 0.6,
            "T1053.005", "lateral-movement", "Remote scheduled task"),
    Pattern("net_use_share", r"net\s+use\s+\\\\\S+", 0.4,
            "T1021.002", "lateral-movement", "Mount remote SMB share"),
    Pattern("ssh_remote", r"\bssh\s+\S+@\S+", 0.3,
            "T1021.004", "lateral-movement", "SSH remote session (Linux)"),

    # ---------------------------------------------------------------- COLLECTION
    Pattern("copy_to_share",
            r"copy\b.*(\.(save|dat|dmp|zip|7z|cab|bak)|\\(temp|windows|appdata)\\).*\\\\", 0.55,
            "T1074", "collection", "Copy of sensitive/staged file to network share"),
    Pattern("compress_staging",
            r"(makecab|compress-archive)\b.*\.(save|dat|dmp|hive|sam|system|ntds)", 0.5,
            "T1560.001", "collection", "Compression of sensitive/staged data"),
    Pattern("archive_create", r"\b(7z|rar|winrar|tar\s+-c[a-z]*f?|zip\s+-r)\b", 0.35,
            "T1560.001", "collection", "Create archive (potential staging)"),
    Pattern("screenshot", r"(get-screenshot|copyfromscreen|screencapture|nircmd.*savescreenshot|import\s+-window)", 0.5,
            "T1113", "collection", "Screen capture"),
    Pattern("clipboard", r"(get-clipboard|xclip\s+-o|pbpaste)", 0.4,
            "T1115", "collection", "Clipboard data capture"),
    Pattern("robocopy_share", r"robocopy.*\\\\", 0.4,
            "T1074", "collection", "robocopy to remote share"),

    # ------------------------------------------------------ COMMAND-AND-CONTROL
    Pattern("certutil_download", r"certutil.*-urlcache.*http", 0.8,
            "T1105", "command-and-control", "certutil download cradle"),
    Pattern("bitsadmin_download", r"bitsadmin.*/transfer", 0.7,
            "T1105", "command-and-control", "bitsadmin download"),
    Pattern("web_download_cradle", r"\b(iwr|invoke-webrequest|wget|curl)\b.*https?://", 0.5,
            "T1105", "command-and-control", "Web download cradle"),
    Pattern("ps_downloadfile", r"(downloadfile|start-bitstransfer|invoke-webrequest.*-outfile)", 0.6,
            "T1105", "command-and-control", "PowerShell file download"),
    Pattern("nc_listener", r"\b(nc|ncat|netcat)\b.*\s-[a-z]*l[a-z]*", 0.7,
            "T1571", "command-and-control", "netcat listener / bind shell"),
    Pattern("nc_connect", r"\b(nc|ncat|netcat)\b\s+\S+\s+[0-9]{2,5}", 0.5,
            "T1095", "command-and-control", "netcat outbound connection"),
    Pattern("dev_tcp_shell", r"/dev/tcp/", 0.8,
            "T1059.004", "command-and-control", "bash /dev/tcp reverse shell"),
    Pattern("ftp_script", r"ftp\s+-s:", 0.5,
            "T1105", "command-and-control", "scripted FTP transfer"),

    # -------------------------------------------------------------- EXFILTRATION
    Pattern("curl_upload", r"\b(curl|wget)\b.*(-T\s|--upload-file|--data-binary\s+@|-d\s+@)", 0.7,
            "T1567", "exfiltration", "HTTP upload exfiltration"),
    Pattern("ps_upload", r"(invoke-restmethod|invoke-webrequest).*-method\s+post.*(-infile|-body)", 0.6,
            "T1567", "exfiltration", "PowerShell HTTP POST exfiltration"),
    Pattern("scp_out", r"\bscp\b\s+\S+\s+\S+@\S+:", 0.5,
            "T1048", "exfiltration", "SCP exfiltration (Linux)"),
    Pattern("rclone", r"\brclone\b.*(copy|sync|move)", 0.7,
            "T1567.002", "exfiltration", "rclone cloud exfiltration"),
    Pattern("dns_tunnel", r"\b(dnscat|iodine|dns2tcp)\b", 0.8,
            "T1048.003", "exfiltration", "DNS tunneling exfiltration"),

    # -------------------------------------------------------------------- IMPACT
    Pattern("vssadmin_delete", r"vssadmin.*delete\s+shadows", 0.9,
            "T1490", "impact", "Volume shadow copy deletion (ransomware)"),
    Pattern("wmic_shadow_delete", r"wmic\s+shadowcopy\s+delete", 0.85,
            "T1490", "impact", "WMIC shadow copy deletion"),
    Pattern("wbadmin_delete", r"wbadmin\s+delete\s+(catalog|systemstatebackup|backup)", 0.85,
            "T1490", "impact", "Delete Windows backups"),
    Pattern("bcdedit_recovery", r"bcdedit.*(recoveryenabled\s+no|bootstatuspolicy\s+ignoreallfailures)", 0.85,
            "T1490", "impact", "Disable Windows recovery (ransomware)"),
    Pattern("cipher_wipe", r"cipher\s+/w", 0.7,
            "T1485", "impact", "Wipe free space"),
    Pattern("format_drive", r"\bformat\s+[a-z]:\s", 0.7,
            "T1485", "impact", "Format drive"),
    Pattern("del_recursive", r"(del\s+/[fsq]+\s|rd\s+/s\s+/q|del\s+.*\\\*\.\*)", 0.5,
            "T1485", "impact", "Recursive file deletion"),
    Pattern("rm_rf_root", r"rm\s+-[a-z]*r[a-z]*f?\s+(/|/\*|~|\$home|/etc|/var)\b", 0.7,
            "T1485", "impact", "Destructive recursive delete (Linux)"),
    Pattern("dd_wipe", r"dd\s+if=/dev/(zero|urandom)\s+of=/dev/", 0.85,
            "T1561", "impact", "Disk wipe via dd (Linux)"),
    Pattern("stop_security_svc", r"(net\s+stop|sc\s+stop|taskkill\s+/f).*(sql|exchange|veeam|backup|defender|sophos|mssql)", 0.6,
            "T1489", "impact", "Stop security/backup services"),
    Pattern("ransom_note", r"(how[\s_-]*to[\s_-]*decrypt|readme.*decrypt|your files.*encrypted|\.(locked|crypted|encrypted)\b)", 0.6,
            "T1486", "impact", "Ransomware encryption / note artifacts"),

    # ============================================================================
    # Expansion pass (LOLBAS / GTFOBins / MITRE / Sigma / Atomic Red Team)
    # ============================================================================
    # ---- additional EXECUTION ----
    Pattern("forfiles_cmd", r"forfiles.*/c\s+[\"']?(cmd|powershell|\S+\.(exe|bat|vbs|ps1))", 0.7,
            "T1059", "execution", "forfiles command execution proxy (LOLBin)"),
    Pattern("pcalua_proxy", r"pcalua(\.exe)?\s+.*-a\b", 0.7,
            "T1218", "execution", "pcalua proxy execution (LOLBin)"),
    Pattern("scriptrunner", r"scriptrunner(\.exe)?\s+.*-appvscript", 0.75,
            "T1218", "execution", "ScriptRunner proxy execution (LOLBin)"),
    Pattern("conhost_proxy", r"conhost(\.exe)?\s+.*--headless", 0.6,
            "T1059", "execution", "conhost.exe headless proxy execution (LOLBin)"),
    Pattern("explorer_proxy", r"explorer(\.exe)?\s+/root,.*\.(exe|scr|dll)", 0.6,
            "T1218", "execution", "explorer.exe child-process proxy execution"),
    Pattern("hh_chm", r"\bhh(\.exe)?\b.*(\.chm|http|javascript:|\.hta)", 0.7,
            "T1218.001", "execution", "hh.exe compiled HTML help / script proxy"),
    Pattern("wmic_xsl", r"wmic\s+.*/format:[\"']?https?://|wmic\s+.*/format:.*\.xsl", 0.8,
            "T1220", "execution", "WMIC XSL script processing (LOLBin)"),
    Pattern("msxsl_exec", r"\bmsxsl(\.exe)?\b", 0.75,
            "T1220", "defense-evasion", "msxsl.exe XSL transform execution (LOLBin)"),
    Pattern("dotnet_jscript", r"\bjsc(\.exe)?\s+.*\.js\b", 0.55,
            "T1059.007", "execution", "JScript .NET compiler execution"),
    Pattern("wsl_exec", r"\b(wsl|bash)(\.exe)?\s+(-e|-c|--exec)\b.*(curl|wget|/dev/tcp|nc\b)", 0.6,
            "T1202", "execution", "WSL/bash.exe indirect command execution"),
    Pattern("perl_revshell", r"perl\s+.*(-e|-mio).*(socket|connect|exec|/bin/(ba)?sh)", 0.8,
            "T1059.004", "execution", "Perl reverse shell / exec (GTFOBins)"),
    Pattern("ruby_revshell", r"ruby\s+-r?socket.*-e|ruby\s+.*tcpsocket.*exec", 0.8,
            "T1059.006", "execution", "Ruby reverse shell (GTFOBins)"),
    Pattern("php_revshell", r"php\s+-r\s+.*(fsockopen|proc_open|exec|shell_exec|/bin/(ba)?sh)", 0.8,
            "T1059.004", "execution", "PHP reverse shell (GTFOBins)"),
    Pattern("awk_revshell", r"awk\s+.*/inet/tcp/", 0.85,
            "T1059.004", "execution", "awk /inet/tcp reverse shell (GTFOBins)"),
    Pattern("socat_revshell", r"\bsocat\b.*(exec:|tcp[46]?:|tcp-listen|pty)", 0.75,
            "T1059.004", "execution", "socat reverse/bind shell (GTFOBins)"),
    Pattern("node_revshell", r"node\s+-e\s+.*(net\.connect|child_process|spawn|/bin/(ba)?sh)", 0.75,
            "T1059.007", "execution", "Node.js reverse shell (GTFOBins)"),
    Pattern("lua_exec", r"lua\s+-e\s+.*os\.execute", 0.6,
            "T1059", "execution", "Lua os.execute shell (GTFOBins)"),
    Pattern("base64_pipe_shell", r"base64\s+-d.*\|\s*(ba)?sh\b|echo\s+\S+\s*\|\s*base64\s+-d\s*\|", 0.8,
            "T1027", "execution", "base64-decode piped to shell (Linux)"),
    Pattern("python_pty_spawn", r"python[0-9.]*\s+-c\s+.*pty\.spawn", 0.7,
            "T1059.006", "execution", "Python pty.spawn TTY upgrade (post-exploit)"),
    Pattern("pager_shell_escape", r"\b(more|less|man|vi|vim|nano|ed)\b.*!\s*(/bin/)?(ba)?sh", 0.45,
            "T1059.004", "privilege-escalation", "Shell escape from pager/editor (GTFOBins)"),

    # ---- additional PERSISTENCE ----
    Pattern("bits_job_persist", r"bitsadmin.*/(setnotifycmdline|addfile.*\.exe|setnotifyflags)", 0.75,
            "T1197", "persistence", "BITS job persistence / notify command"),
    Pattern("netsh_helper_dll", r"netsh\s+.*add\s+helper\b", 0.75,
            "T1546.007", "persistence", "netsh helper DLL persistence"),
    Pattern("com_hijack", r"reg\s+add.*\\(clsid|classes)\\.*\\(inprocserver32|localserver32)", 0.6,
            "T1546.015", "persistence", "COM object hijacking (CLSID server)"),
    Pattern("port_monitor", r"reg\s+add.*\\control\\print\\monitors\\", 0.7,
            "T1547.010", "persistence", "Port monitor DLL persistence"),
    Pattern("screensaver_persist", r"reg\s+add.*\\control\s+panel\\desktop.*scrnsave\.exe", 0.6,
            "T1546.002", "persistence", "Screensaver persistence"),
    Pattern("logon_script_persist", r"reg\s+add.*\\environment.*userinitmprlogonscript", 0.7,
            "T1037.001", "persistence", "Logon script (UserInitMprLogonScript) persistence"),
    Pattern("time_provider", r"reg\s+add.*\\services\\w32time\\timeproviders\\", 0.7,
            "T1547.003", "persistence", "Time provider DLL persistence"),
    Pattern("lsa_security_provider", r"reg\s+add.*\\control\\lsa.*(security packages|sso)", 0.75,
            "T1547.005", "persistence", "LSASS security/authentication package persistence"),
    Pattern("appinit_dll", r"reg\s+add.*windows\s+nt\\currentversion\\windows.*appinit_dlls", 0.75,
            "T1546.010", "persistence", "AppInit_DLLs persistence"),
    Pattern("ifeo_silentprocess", r"image file execution options.*globalflag|silentprocessexit.*monitorprocess", 0.75,
            "T1546.012", "persistence", "IFEO GlobalFlag / SilentProcessExit persistence"),
    Pattern("launchctl_persist", r"launchctl\s+(load|bootstrap|enable|submit)\b|/library/launch(agents|daemons)/\S+\.plist", 0.6,
            "T1543.001", "persistence", "macOS LaunchAgent/LaunchDaemon persistence"),
    Pattern("ldso_preload", r"(/etc/ld\.so\.preload|ld_preload=)", 0.7,
            "T1574.006", "persistence", "ld.so.preload / LD_PRELOAD hijack (Linux)"),
    Pattern("rc_local_persist", r">>?\s*/etc/(rc\.local|rc\.d/|init\.d/)", 0.55,
            "T1037.004", "persistence", "rc.local / init script persistence (Linux)"),
    Pattern("dylib_insert", r"dyld_insert_libraries=", 0.7,
            "T1574.006", "persistence", "macOS DYLD_INSERT_LIBRARIES hijack"),

    # ---- additional PRIVILEGE ESCALATION ----
    Pattern("cmstp_uac", r"\bcmstp(\.exe)?\b.*(/s|/au|\.inf)", 0.75,
            "T1218.003", "privilege-escalation", "cmstp.exe UAC bypass / proxy execution"),
    Pattern("sudo_gtfobins", r"sudo\s+(-l\b|.*\b(vim|vi|nmap|find|awk|perl|python|less|man|env|tee|tar)\b.*(!|\bsystem\b|/bin/(ba)?sh|exec))", 0.55,
            "T1548.003", "privilege-escalation", "sudo abuse via GTFOBins helper"),
    Pattern("setcap_abuse", r"setcap\s+(cap_setuid|cap_dac_read_search|cap_sys_admin)", 0.6,
            "T1548.001", "privilege-escalation", "Linux capability abuse via setcap"),
    Pattern("pkexec_abuse", r"\bpkexec\b", 0.4,
            "T1548", "privilege-escalation", "pkexec (PwnKit/polkit) privilege escalation"),
    Pattern("dll_search_hijack", r"copy\b.*\.dll\s+.*\\(system32|syswow64)\\\S+\.dll", 0.4,
            "T1574.001", "privilege-escalation", "DLL search-order hijack staging"),

    # ---- additional DEFENSE EVASION ----
    Pattern("clear_content_logs", r"(clear-content|set-content).*\.(log|evtx)\b|cp\s+/dev/null\s+", 0.55,
            "T1070", "defense-evasion", "Truncate/clear log files"),
    Pattern("bcdedit_safeboot", r"bcdedit.*\bsafeboot\b", 0.7,
            "T1562.009", "defense-evasion", "Boot to Safe Mode to evade defenses"),
    Pattern("etw_patch", r"(etweventwrite|ntdll.*etw|set-etwtraceprovider.*-enabled\s+0|logman\s+stop)", 0.75,
            "T1562.006", "defense-evasion", "ETW provider tampering / patching"),
    Pattern("disable_amsi_providers", r"reg\s+(add|delete).*\\amsi\\providers", 0.8,
            "T1562.001", "defense-evasion", "Remove/disable AMSI providers"),
    Pattern("sysmon_unload", r"(sysmon\s+-u|fltmc\s+unload|sc\s+(stop|delete)\s+sysmon)", 0.8,
            "T1562.001", "defense-evasion", "Unload Sysmon / minifilter driver"),
    Pattern("verclsid_proxy", r"\bverclsid(\.exe)?\b.*/s", 0.6,
            "T1218.012", "defense-evasion", "verclsid.exe COM proxy execution (LOLBin)"),
    Pattern("syncappvpublishing", r"syncappvpublishingserver(\.vbs|\.exe)?.*;", 0.8,
            "T1218", "defense-evasion", "SyncAppvPublishingServer PowerShell proxy"),
    Pattern("regasm_regsvcs", r"\b(regasm|regsvcs)(\.exe)?\b.*\.(dll|exe)", 0.6,
            "T1218.009", "defense-evasion", "regasm/regsvcs assembly proxy execution"),
    Pattern("odbcconf_dll", r"odbcconf(\.exe)?\s+.*(/a|regsvr|\.rsp)", 0.7,
            "T1218.008", "defense-evasion", "odbcconf DLL proxy execution (LOLBin)"),
    Pattern("xwizard_proxy", r"\bxwizard(\.exe)?\b.*runwizard", 0.6,
            "T1218", "defense-evasion", "xwizard.exe COM proxy execution (LOLBin)"),
    Pattern("certutil_encode", r"certutil.*-encode", 0.5,
            "T1027", "defense-evasion", "certutil base64-encode payload"),
    Pattern("injection_apis", r"(create_suspended|setthreadcontext|writeprocessmemory|ntunmapviewofsection|virtualallocex|queueuserapc)", 0.7,
            "T1055.012", "defense-evasion", "Process hollowing/injection API indicators"),

    # ---- additional CREDENTIAL ACCESS ----
    Pattern("shadowcopy_sam", r"copy\b.*\\\\\?\\globalroot\\device\\harddiskvolumeshadowcopy", 0.85,
            "T1003.002", "credential-access", "SAM/SYSTEM theft via volume shadow copy"),
    Pattern("wdigest_enable", r"reg\s+add.*\\securityproviders\\wdigest.*uselogoncredential", 0.85,
            "T1112", "credential-access", "Enable WDigest cleartext credential caching"),
    Pattern("pwdump_gsecdump", r"\b(pwdump[0-9]?|gsecdump|fgdump|wce)\b", 0.9,
            "T1003.002", "credential-access", "pwdump/gsecdump/wce credential dumper"),
    Pattern("nppspy", r"\bnppspy\b|reg\s+add.*\\networkprovider\\order", 0.7,
            "T1003", "credential-access", "NPPSpy network provider credential capture"),
    Pattern("dpapi_masterkey", r"(dpapi::|sharpdpapi|backupkey|\\protect\\.*s-1-5)", 0.75,
            "T1555.004", "credential-access", "DPAPI masterkey / secret extraction"),
    Pattern("rubeus_tickets", r"\brubeus\b.*(asktgt|dump|tgtdeleg|monitor|harvest|ptt)", 0.85,
            "T1558", "credential-access", "Rubeus Kerberos ticket abuse"),
    Pattern("ssh_key_harvest", r"(cat|cp|find|tar)\b.*\.ssh/(id_rsa|id_ed25519|id_ecdsa|id_dsa)\b", 0.6,
            "T1552.004", "credential-access", "Harvest private SSH keys (Linux)"),
    Pattern("cloud_cred_files", r"(\.aws/credentials|\.azure/accesstokens|gcloud/.*credentials|\.kube/config)\b", 0.6,
            "T1552.001", "credential-access", "Read cloud/k8s credential files"),
    Pattern("keychain_dump", r"security\s+(dump-keychain|find-(generic|internet)-password)", 0.7,
            "T1555.001", "credential-access", "macOS Keychain credential dump"),

    # ---- additional DISCOVERY ----
    Pattern("recon_cloud_metadata", r"169\.254\.169\.254|metadata\.google\.internal|/latest/meta-data/", 0.55,
            "T1552.005", "discovery", "Cloud instance metadata (IMDS) access"),
    Pattern("recon_kube_enum", r"kubectl\s+(get|describe)\s+(secrets|serviceaccounts)\b", 0.4,
            "T1613", "discovery", "Kubernetes secret/SA enumeration"),

    # ---- additional LATERAL MOVEMENT ----
    Pattern("kubectl_exec", r"kubectl\s+exec\b", 0.6,
            "T1609", "lateral-movement", "kubectl exec into container"),
    Pattern("docker_privileged", r"docker\s+run\b.*(--privileged|-v\s+/:/|--pid=host|--net=host|--cap-add)", 0.7,
            "T1610", "lateral-movement", "Privileged container / host mount escape"),
    Pattern("docker_socket_mount", r"-v\s+/var/run/docker\.sock", 0.7,
            "T1610", "privilege-escalation", "Mount docker socket for host escape"),
    Pattern("dcom_lateral", r"(mmc20\.application|shellwindows|shellbrowserwindow|excel\.application).*createinstance|invoke-dcom", 0.7,
            "T1021.003", "lateral-movement", "DCOM lateral movement"),

    # ---- additional COMMAND-AND-CONTROL ----
    Pattern("dnscmd_serverlevelplugin", r"dnscmd.*serverlevelplugindll", 0.85,
            "T1574.001", "command-and-control", "dnscmd ServerLevelPluginDll load (LOLBin)"),
    Pattern("ssh_tunnel", r"ssh\s+.*-[a-z]*[rld]\s+\S*[0-9]+:", 0.55,
            "T1572", "command-and-control", "SSH port-forward / tunnel"),
    Pattern("reverse_proxy_tool", r"\b(chisel|ngrok|frpc|gost|revsocks|plink)\b", 0.7,
            "T1572", "command-and-control", "Tunneling/reverse-proxy tooling"),
    Pattern("certreq_download", r"certreq.*-(post|config)\b.*https?://", 0.7,
            "T1105", "command-and-control", "certreq.exe download/upload (LOLBin)"),

    # ---- additional EXFILTRATION ----
    Pattern("dns_exfil_nslookup", r"(nslookup|dig|host)\s+.*\$\(.*\)|for\b.*nslookup.*%", 0.5,
            "T1048.003", "exfiltration", "DNS exfiltration via nslookup/dig loop"),
    Pattern("cloud_cli_exfil", r"\b(aws\s+s3\s+(cp|sync|mv)|az\s+storage\s+blob\s+upload|gsutil\s+cp|gcloud\s+storage\s+cp)\b", 0.5,
            "T1567.002", "exfiltration", "Cloud-storage CLI exfiltration"),

    # ---- additional IMPACT ----
    Pattern("fsutil_set_zero", r"fsutil\s+file\s+setzerodata", 0.7,
            "T1485", "impact", "Zero out file data (fsutil)"),
    Pattern("diskpart_clean", r"diskpart\b.*\bclean\b|\bclean\s+all\b", 0.6,
            "T1561.002", "impact", "Wipe disk via diskpart clean"),
    Pattern("crypto_miner", r"\b(xmrig|minerd|cgminer)\b|stratum\+tcp://|--cpu-priority", 0.8,
            "T1496", "impact", "Cryptocurrency miner execution"),
    Pattern("recovery_disable_ps", r"(disable-computerrestore|reagentc\s+/disable)", 0.8,
            "T1490", "impact", "Disable system restore / recovery"),
    Pattern("encrypt_files_bulk", r"\bcipher\s+/e\b|gpg\s+.*--(encrypt|symmetric).*\*|openssl\s+enc\s+-(aes|e)\b.*-in\s+", 0.5,
            "T1486", "impact", "Bulk file encryption (potential ransomware)"),
]
