# sentry/knowledge/standalone.py
from sentry.models import Pattern

STANDALONE_PATTERNS: list[Pattern] = [
    Pattern("enc_powershell", r"powershell.*\s-e(nc|ncodedcommand)?\b", 0.7,
            "T1059.001", "execution", "PowerShell encoded command"),
    Pattern("hidden_window", r"-w(indowstyle)?\s+hidden", 0.4,
            "T1564", "defense-evasion", "Hidden window"),
    Pattern("nop_profile", r"-nop(rofile)?\b", 0.3,
            "T1059.001", "execution", "PowerShell no-profile"),
    Pattern("certutil_download", r"certutil.*-urlcache.*http", 0.8,
            "T1105", "command-and-control", "certutil download cradle"),
    Pattern("bitsadmin_download", r"bitsadmin.*/transfer", 0.7,
            "T1105", "command-and-control", "bitsadmin download"),
    Pattern("sam_dump", r"reg\s+save\s+hklm\\sam", 0.9,
            "T1003.002", "credential-access", "SAM hive dump"),
    Pattern("lsass_dump", r"(procdump.*lsass|comsvcs.*minidump)", 0.95,
            "T1003.001", "credential-access", "LSASS memory dump"),
    Pattern("mimikatz", r"sekurlsa|mimikatz|logonpasswords", 0.95,
            "T1003.001", "credential-access", "Mimikatz credential theft"),
    Pattern("schtasks_create", r"schtasks.*/create", 0.5,
            "T1053.005", "persistence", "Scheduled task creation"),
    Pattern("reg_runkey", r"reg\s+add.*\\currentversion\\run", 0.6,
            "T1547.001", "persistence", "Run key persistence"),
    Pattern("net_user_add", r"net\s+user\s+\S+\s+\S+\s+/add", 0.6,
            "T1136.001", "persistence", "Local account creation"),
    Pattern("download_cradle", r"(iwr|invoke-webrequest|wget|curl).*http", 0.5,
            "T1105", "command-and-control", "Web download cradle"),
    Pattern("iex_download", r"iex\s*\(.*(downloadstring|iwr)", 0.85,
            "T1059.001", "execution", "IEX download-and-execute"),
    Pattern("vssadmin_delete", r"vssadmin.*delete\s+shadows", 0.9,
            "T1490", "impact", "Shadow copy deletion (ransomware)"),
    Pattern("bcdedit_recovery", r"bcdedit.*recoveryenabled\s+no", 0.85,
            "T1490", "impact", "Disable recovery (ransomware)"),
    Pattern("wevtutil_clear", r"wevtutil\s+cl", 0.7,
            "T1070.001", "defense-evasion", "Clear event logs"),
    Pattern("rundll32_suspicious", r"rundll32.*javascript:", 0.8,
            "T1218.011", "defense-evasion", "rundll32 proxy execution"),
    Pattern("wmic_process_call", r"wmic\s+process\s+call\s+create", 0.6,
            "T1047", "execution", "WMI process create"),
    Pattern("encoded_blob", r"[a-z0-9+/]{60,}={0,2}", 0.4,
            "T1027", "defense-evasion", "Long encoded blob"),
    Pattern("temp_exec", r"\\(temp|appdata|programdata)\\[^\s]+\.(exe|ps1|bat|vbs)", 0.4,
            "T1036", "defense-evasion", "Execution from temp/appdata"),
    Pattern("copy_to_share", r"copy\b.+\\\\\S+", 0.75,
            "T1039", "exfiltration", "Copy to network share (data staging/exfil)"),
]
